### ISSUE TITLE
travis.yml needs skip_cleanup command to deploy correctly

### ISSUE THREAD

**Issue by loama** [immnk/aradhana-api#11]
add skip_cleanup: true inside the deploy stage in travis.yml

``` bash
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $PRODUCTION_FIREBASE_TOKEN
    project: "aradhana-api"
```

**Comment by immnk** [comment]
This doesn't resolve my issue for 401 authentication error while deploying. https://travis-ci.org/immnk/aradhana-api/jobs/467305044/config

**Comment by immnk** [comment]
doesnt work
